import type { MerchantEvent } from '@/shared/types';

// ══════════════════════════════════════════════════════════════
//  Saudi Events Encyclopedia - 53 Events
//  Maham Expo - موسوعة الفعاليات السعودية
// ══════════════════════════════════════════════════════════════

export const saudiEventsDatabase: MerchantEvent[] = [
  // ─── 1. Entertainment & Seasons (ترفيه ومواسم) ─────────────
  {
    id: 'ev-001',
    name: 'موسم الرياض 2025-2026',
    nameEn: 'Riyadh Season 2025-2026',
    description: 'أضخم حدث ترفيهي في المنطقة يضم مجموعة متنوعة من الفعاليات الترفيهية والثقافية والرياضية عبر مناطق متعددة تجذب ملايين الزوار من حول العالم.',
    descriptionEn: 'The biggest entertainment event in the region featuring diverse entertainment, cultural, and sports activities across multiple zones attracting millions of visitors worldwide.',
    location: 'بوليفارد وورلد، بوليفارد سيتي، المملكة أرينا',
    city: 'الرياض',
    startDate: '2025-10-10',
    endDate: '2026-03-31',
    availableBooths: 85,
    totalBooths: 500,
    type: 'entertainment',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1663900108404-a05e8bf82cda?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 12000000, exhibitors: 1200, area: 500000 },
  },
  {
    id: 'ev-002',
    name: 'بوليفارد وورلد',
    nameEn: 'Boulevard World',
    description: 'منطقة ترفيهية عالمية تضم تجارب من أكثر من 20 دولة حول العالم مع مطاعم ومتاجر ومسارح وعروض حية على مدار الموسم.',
    descriptionEn: 'A world-class entertainment zone featuring experiences from over 20 countries with restaurants, shops, theaters, and live shows throughout the season.',
    location: 'بوليفارد وورلد، طريق الأمير تركي بن عبدالعزيز الأول',
    city: 'الرياض',
    startDate: '2025-10-15',
    endDate: '2026-03-31',
    availableBooths: 45,
    totalBooths: 200,
    type: 'entertainment',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 5000000, exhibitors: 600, area: 120000 },
  },
  {
    id: 'ev-003',
    name: 'بوليفارد سيتي',
    nameEn: 'Boulevard City',
    description: 'وجهة ترفيهية متكاملة في قلب الرياض تجمع بين المتاجر الفاخرة والمطاعم العالمية والعروض الترفيهية المبهرة.',
    descriptionEn: 'A comprehensive entertainment destination in the heart of Riyadh combining luxury shops, international restaurants, and spectacular entertainment shows.',
    location: 'بوليفارد سيتي، حي حطين',
    city: 'الرياض',
    startDate: '2025-10-15',
    endDate: '2026-03-31',
    availableBooths: 35,
    totalBooths: 150,
    type: 'entertainment',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 4000000, exhibitors: 400, area: 80000 },
  },
  {
    id: 'ev-004',
    name: 'موسم جدة 2026',
    nameEn: 'Jeddah Season 2026',
    description: 'فعالية ترفيهية ساحلية ضخمة على ضفاف البحر الأحمر تجمع بين المهرجانات الموسيقية والعروض المائية والمعارض الفنية والمطاعم.',
    descriptionEn: 'A massive coastal entertainment event on the Red Sea shores combining music festivals, water shows, art exhibitions, and restaurants.',
    location: 'الواجهة البحرية، أبحر الشمالية',
    city: 'جدة',
    startDate: '2026-05-15',
    endDate: '2026-07-31',
    availableBooths: 60,
    totalBooths: 300,
    type: 'entertainment',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 6000000, exhibitors: 800, area: 200000 },
  },
  {
    id: 'ev-005',
    name: 'موسم العلا (شتاء طنطورة)',
    nameEn: 'AlUla Season (Winter at Tantora)',
    description: 'تجربة ثقافية وترفيهية فريدة في قلب الصحراء السعودية بين المواقع الأثرية التاريخية مع حفلات موسيقية عالمية وفعاليات فنية.',
    descriptionEn: 'A unique cultural and entertainment experience in the heart of Saudi desert among historical archaeological sites with world-class concerts and art events.',
    location: 'العلا، مدائن صالح',
    city: 'العلا',
    startDate: '2025-12-01',
    endDate: '2026-02-28',
    availableBooths: 0,
    totalBooths: 80,
    type: 'cultural',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 800000, exhibitors: 200, area: 50000 },
  },
  {
    id: 'ev-006',
    name: 'موسم الخبر 2025-2026',
    nameEn: 'Al Khobar Season 2025-2026',
    description: 'فعالية ترفيهية شاملة في المنطقة الشرقية تقدم تجارب متنوعة تشمل المطاعم والحفلات والأنشطة العائلية على شاطئ الخليج.',
    descriptionEn: 'A comprehensive entertainment event in the Eastern Region offering diverse experiences including restaurants, concerts, and family activities on the Gulf shore.',
    location: 'كورنيش الخبر',
    city: 'الخبر',
    startDate: '2025-10-20',
    endDate: '2026-04-15',
    availableBooths: 30,
    totalBooths: 120,
    type: 'entertainment',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 2000000, exhibitors: 300, area: 60000 },
  },
  {
    id: 'ev-007',
    name: 'فعالية على خطاه',
    nameEn: 'Ala Khutah',
    description: 'رحلة من مكة المكرمة إلى المدينة المنورة عبر 8 مناطق استراتيجية. احجز بوثك في أكبر فعاليات الرياض الموسمية واستفد من مواقع مميزة للمطاعم والتجزئة.',
    descriptionEn: 'A journey from Makkah to Madinah through 8 strategic zones. Book your booth in one of the largest seasonal events and benefit from prime locations for restaurants and retail.',
    location: 'مكة المكرمة - المدينة المنورة',
    city: 'مكة المكرمة',
    startDate: '2026-03-01',
    endDate: '2026-03-30',
    availableBooths: 24,
    totalBooths: 120,
    type: 'cultural',
    status: 'active',
    image: 'https://mmnews.tv/wp-content/uploads/2026/02/Ala-Khutah-project.webp',
    stats: { expectedVisitors: 1500000, exhibitors: 350, area: 100000 },
  },
  {
    id: 'ev-008',
    name: 'مهرجان مدل بيست (Soundstorm)',
    nameEn: 'MDLBEAST Soundstorm',
    description: 'أكبر مهرجان موسيقي في الشرق الأوسط يجمع أبرز الفنانين العالميين والمحليين في تجربة موسيقية لا مثيل لها تستقطب جمهوراً من أكثر من 100 دولة.',
    descriptionEn: 'The largest music festival in the Middle East featuring top global and local artists in an unparalleled musical experience attracting audiences from over 100 countries.',
    location: 'بانبان، شمال الرياض',
    city: 'الرياض',
    startDate: '2025-12-12',
    endDate: '2025-12-14',
    availableBooths: 0,
    totalBooths: 250,
    type: 'entertainment',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 750000, exhibitors: 150, area: 200000 },
  },
  {
    id: 'ev-009',
    name: 'قرية زمان',
    nameEn: 'Zaman Village',
    description: 'تجربة تراثية سعودية أصيلة تعيد إحياء الحياة القديمة مع أسواق تقليدية ومأكولات شعبية وعروض فلكلورية في أجواء تاريخية.',
    descriptionEn: 'An authentic Saudi heritage experience reviving old life with traditional markets, folk cuisine, and folklore shows in a historical atmosphere.',
    location: 'منطقة زمان، موسم الرياض',
    city: 'الرياض',
    startDate: '2025-10-20',
    endDate: '2026-03-31',
    availableBooths: 15,
    totalBooths: 60,
    type: 'cultural',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1466442929976-97f336a657be?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 1000000, exhibitors: 180, area: 30000 },
  },
  {
    id: 'ev-010',
    name: 'منطقة فيا رياض (Via Riyadh)',
    nameEn: 'Via Riyadh',
    description: 'وجهة ترفيهية حديثة تمتد على طول 5 كم تضم مطاعم ومقاهي ومتاجر فاخرة وأماكن ترفيهية متنوعة في بيئة مفتوحة.',
    descriptionEn: 'A modern entertainment destination stretching 5km featuring restaurants, cafes, luxury shops, and various entertainment venues in an open environment.',
    location: 'فيا رياض، طريق الملك سلمان',
    city: 'الرياض',
    startDate: '2025-11-01',
    endDate: '2026-12-31',
    availableBooths: 20,
    totalBooths: 100,
    type: 'entertainment',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 3000000, exhibitors: 250, area: 150000 },
  },
  {
    id: 'ev-011',
    name: 'حديقة الحيوانات بالرياض',
    nameEn: 'Riyadh Zoo',
    description: 'حديقة حيوانات حديثة ومطورة تضم أكثر من 1500 حيوان من 190 نوعاً مع مناطق ترفيهية وتعليمية للعائلات.',
    descriptionEn: 'A modern and developed zoo housing over 1500 animals from 190 species with entertainment and educational zones for families.',
    location: 'حي الملز، الرياض',
    city: 'الرياض',
    startDate: '2025-10-10',
    endDate: '2026-03-31',
    availableBooths: 10,
    totalBooths: 40,
    type: 'entertainment',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 500000, exhibitors: 50, area: 55000 },
  },
  {
    id: 'ev-012',
    name: 'منطقة وندر جاردن',
    nameEn: 'Wonder Garden',
    description: 'حديقة خيالية مضيئة تقدم تجربة بصرية مذهلة مع عروض ضوئية وتركيبات فنية تفاعلية في أجواء ساحرة.',
    descriptionEn: 'A magical illuminated garden offering a stunning visual experience with light shows and interactive art installations in an enchanting atmosphere.',
    location: 'وندر جاردن، الرياض',
    city: 'الرياض',
    startDate: '2025-10-20',
    endDate: '2026-03-31',
    availableBooths: 12,
    totalBooths: 45,
    type: 'entertainment',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 800000, exhibitors: 80, area: 25000 },
  },
  {
    id: 'ev-013',
    name: 'مهرجان الكليجا',
    nameEn: 'Kleicha Festival',
    description: 'مهرجان تراثي يحتفي بصناعة الكليجا التقليدية في بريدة مع عروض طبخ حي ومسابقات وأسواق شعبية.',
    descriptionEn: 'A heritage festival celebrating traditional Kleicha making in Buraydah with live cooking shows, competitions, and folk markets.',
    location: 'منطقة المهرجانات، بريدة',
    city: 'بريدة',
    startDate: '2026-01-15',
    endDate: '2026-02-15',
    availableBooths: 0,
    totalBooths: 100,
    type: 'cultural',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 300000, exhibitors: 120, area: 15000 },
  },
  {
    id: 'ev-014',
    name: 'مهرجان الورد الطائفي',
    nameEn: 'Taif Rose Festival',
    description: 'مهرجان سنوي يحتفي بموسم حصاد الورد الطائفي الشهير مع عروض للعطور والمنتجات الطبيعية ومعارض فنية.',
    descriptionEn: 'An annual festival celebrating the famous Taif rose harvest season with perfume exhibitions, natural products, and art shows.',
    location: 'منتزه الردف، الطائف',
    city: 'الطائف',
    startDate: '2026-04-01',
    endDate: '2026-04-20',
    availableBooths: 40,
    totalBooths: 80,
    type: 'cultural',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 500000, exhibitors: 150, area: 20000 },
  },
  {
    id: 'ev-015',
    name: 'مهرجان التمور',
    nameEn: 'Dates Festival',
    description: 'أكبر مهرجان للتمور في العالم يجمع المزارعين والتجار من أنحاء المملكة لعرض أفضل أنواع التمور السعودية.',
    descriptionEn: 'The world\'s largest dates festival gathering farmers and traders from across the Kingdom to showcase the best Saudi date varieties.',
    location: 'سوق التمور، بريدة',
    city: 'بريدة',
    startDate: '2026-08-01',
    endDate: '2026-09-15',
    availableBooths: 70,
    totalBooths: 200,
    type: 'exhibition',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1596591606975-97ee5cef3a1e?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 400000, exhibitors: 500, area: 30000 },
  },

  // ─── 2. Tech & Business (تقنية وأعمال) ─────────────────────
  {
    id: 'ev-016',
    name: 'مؤتمر LEAP 2026',
    nameEn: 'LEAP 2026',
    description: 'أحد أكبر المؤتمرات التقنية في العالم. يجمع قادة التقنية والابتكار والشركات الناشئة من أكثر من 170 دولة في منصة واحدة.',
    descriptionEn: 'One of the world\'s largest technology conferences bringing together tech leaders, innovators, and startups from over 170 countries on one platform.',
    location: 'مركز الرياض الدولي للمؤتمرات والمعارض',
    city: 'الرياض',
    startDate: '2026-03-13',
    endDate: '2026-03-16',
    availableBooths: 60,
    totalBooths: 300,
    type: 'technology',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 250000, exhibitors: 900, area: 100000 },
  },
  {
    id: 'ev-017',
    name: 'منتدى المعادن المستقبلية 2026',
    nameEn: 'Future Minerals Forum 2026',
    description: 'منتدى عالمي يجمع قادة صناعة التعدين والمعادن لمناقشة مستقبل القطاع وفرص الاستثمار في المملكة العربية السعودية.',
    descriptionEn: 'A global forum bringing together mining and minerals industry leaders to discuss the sector\'s future and investment opportunities in Saudi Arabia.',
    location: 'مركز الملك عبدالعزيز الدولي للمؤتمرات',
    city: 'الرياض',
    startDate: '2026-01-14',
    endDate: '2026-01-16',
    availableBooths: 0,
    totalBooths: 150,
    type: 'conference',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 50000, exhibitors: 200, area: 40000 },
  },
  {
    id: 'ev-018',
    name: 'معرض المدن الذكية - السعودية',
    nameEn: 'Smart Cities Expo Saudi',
    description: 'فعالية تجمع كبار الموردين والخبراء في حلول المدن الذكية والتقنيات الحضرية المتقدمة ضمن رؤية 2030.',
    descriptionEn: 'An event bringing together top suppliers and experts in smart city solutions and advanced urban technologies within Vision 2030.',
    location: 'مركز الرياض الدولي للمؤتمرات',
    city: 'الرياض',
    startDate: '2026-11-10',
    endDate: '2026-11-13',
    availableBooths: 35,
    totalBooths: 140,
    type: 'technology',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 60000, exhibitors: 250, area: 35000 },
  },
  {
    id: 'ev-019',
    name: 'مؤتمر الفضاء العالمي',
    nameEn: 'International Astronautical Congress',
    description: 'مؤتمر دولي رائد يستعرض أحدث الابتكارات في علوم الفضاء والأقمار الصناعية وتكنولوجيا الاستكشاف الفضائي.',
    descriptionEn: 'A leading international congress showcasing the latest innovations in space science, satellites, and space exploration technology.',
    location: 'مركز الملك عبدالعزيز الدولي للمؤتمرات',
    city: 'الرياض',
    startDate: '2026-10-15',
    endDate: '2026-10-19',
    availableBooths: 40,
    totalBooths: 120,
    type: 'technology',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 35000, exhibitors: 180, area: 30000 },
  },
  {
    id: 'ev-020',
    name: 'معرض الطاقة الشمسية وتخزين الطاقة',
    nameEn: 'Solar & Energy Storage Exhibition',
    description: 'معرض يركز على حلول الطاقة المتجددة والطاقة الشمسية وتقنيات تخزين الطاقة المتقدمة في إطار رؤية السعودية 2030.',
    descriptionEn: 'An exhibition focusing on renewable energy solutions, solar power, and advanced energy storage technologies within Saudi Vision 2030.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2026-09-22',
    endDate: '2026-09-24',
    availableBooths: 28,
    totalBooths: 100,
    type: 'exhibition',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 25000, exhibitors: 150, area: 20000 },
  },
  {
    id: 'ev-021',
    name: 'المؤتمر السعودي البحري 2026',
    nameEn: 'Saudi Maritime Congress 2026',
    description: 'مؤتمر متخصص في القطاع البحري يستعرض أحدث التقنيات والفرص في الصناعات البحرية والموانئ والنقل البحري.',
    descriptionEn: 'A specialized maritime congress showcasing the latest technologies and opportunities in maritime industries, ports, and marine transport.',
    location: 'مركز المؤتمرات',
    city: 'الدمام',
    startDate: '2026-09-16',
    endDate: '2026-09-17',
    availableBooths: 20,
    totalBooths: 80,
    type: 'conference',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1724364552281-dbed323c4633?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 15000, exhibitors: 100, area: 15000 },
  },
  {
    id: 'ev-022',
    name: 'معرض ومؤتمر الصحة العالمي',
    nameEn: 'Global Health Exhibition',
    description: 'أكبر تجمع للقطاع الصحي في المنطقة يجمع شركات الأدوية والمعدات الطبية ومقدمي الخدمات الصحية من حول العالم.',
    descriptionEn: 'The largest healthcare gathering in the region bringing together pharmaceutical companies, medical equipment firms, and healthcare providers worldwide.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2026-10-20',
    endDate: '2026-10-22',
    availableBooths: 50,
    totalBooths: 200,
    type: 'conference',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 40000, exhibitors: 350, area: 45000 },
  },
  {
    id: 'ev-023',
    name: 'منتدى الاستثمار السياحي',
    nameEn: 'Tourism Investment Forum',
    description: 'منتدى يجمع المستثمرين وصناع القرار في قطاع السياحة لاستعراض فرص الاستثمار السياحي في المملكة.',
    descriptionEn: 'A forum bringing together investors and decision makers in the tourism sector to explore tourism investment opportunities in the Kingdom.',
    location: 'فندق الفيصلية',
    city: 'الرياض',
    startDate: '2026-05-10',
    endDate: '2026-05-12',
    availableBooths: 25,
    totalBooths: 80,
    type: 'conference',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 20000, exhibitors: 120, area: 15000 },
  },
  {
    id: 'ev-024',
    name: 'معرض CIPS MENA',
    nameEn: 'CIPS MENA 2026',
    description: 'معرض ومؤتمر متخصص في إدارة سلاسل الإمداد والمشتريات يجمع أبرز الخبراء والشركات في المنطقة.',
    descriptionEn: 'A specialized exhibition and conference in supply chain management and procurement bringing together top experts and companies in the region.',
    location: 'مركز الرياض الدولي للمؤتمرات',
    city: 'الرياض',
    startDate: '2026-04-15',
    endDate: '2026-04-17',
    availableBooths: 22,
    totalBooths: 90,
    type: 'conference',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 15000, exhibitors: 130, area: 18000 },
  },
  {
    id: 'ev-025',
    name: 'قمة بروبتك العالمية 2026',
    nameEn: 'PropTech Global Summit 2026',
    description: 'قمة عالمية تركز على التقنيات العقارية والحلول الرقمية لقطاع العقارات مع مشاركين من أكثر من 50 دولة.',
    descriptionEn: 'A global summit focusing on real estate technology and digital solutions for the property sector with participants from over 50 countries.',
    location: 'مركز الملك عبدالعزيز الدولي للمؤتمرات',
    city: 'الرياض',
    startDate: '2026-10-08',
    endDate: '2026-10-10',
    availableBooths: 30,
    totalBooths: 100,
    type: 'technology',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 20000, exhibitors: 160, area: 22000 },
  },
  {
    id: 'ev-026',
    name: 'معرض ومؤتمر التعدين الدولي',
    nameEn: 'International Mining Conference & Exhibition',
    description: 'معرض شامل لقطاع التعدين يستعرض أحدث المعدات والتقنيات وفرص الاستثمار في الثروات المعدنية السعودية.',
    descriptionEn: 'A comprehensive mining exhibition showcasing the latest equipment, technologies, and investment opportunities in Saudi mineral resources.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2026-01-12',
    endDate: '2026-01-14',
    availableBooths: 0,
    totalBooths: 130,
    type: 'exhibition',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 30000, exhibitors: 200, area: 25000 },
  },
  {
    id: 'ev-027',
    name: 'ملتقى بيبان',
    nameEn: 'Biban Forum',
    description: 'أكبر ملتقى لرواد الأعمال في المنطقة يدعم المشاريع الصغيرة والمتوسطة ويجمع المستثمرين وأصحاب المشاريع الناشئة.',
    descriptionEn: 'The largest entrepreneurs forum in the region supporting SMEs and bringing together investors and startup founders.',
    location: 'واجهة الرياض',
    city: 'الرياض',
    startDate: '2026-11-15',
    endDate: '2026-11-19',
    availableBooths: 45,
    totalBooths: 180,
    type: 'conference',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 100000, exhibitors: 400, area: 50000 },
  },
  {
    id: 'ev-028',
    name: 'معرض الدفاع العالمي',
    nameEn: 'World Defense Show',
    description: 'معرض دفاعي عالمي يجمع أبرز شركات الصناعات الدفاعية والأمنية من حول العالم لعرض أحدث التقنيات والمعدات.',
    descriptionEn: 'A global defense exhibition bringing together top defense and security industry companies worldwide to showcase the latest technologies and equipment.',
    location: 'منطقة المعارض، الرياض',
    city: 'الرياض',
    startDate: '2026-02-08',
    endDate: '2026-02-12',
    availableBooths: 0,
    totalBooths: 250,
    type: 'exhibition',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1580752300992-559f8e0734e0?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 80000, exhibitors: 600, area: 80000 },
  },
  {
    id: 'ev-029',
    name: 'مؤتمر مبادرة مستقبل الاستثمار (FII)',
    nameEn: 'Future Investment Initiative (FII)',
    description: 'مؤتمر استثماري عالمي رفيع المستوى يجمع قادة الأعمال والمستثمرين وصناع القرار لمناقشة مستقبل الاقتصاد العالمي.',
    descriptionEn: 'A high-level global investment conference bringing together business leaders, investors, and decision makers to discuss the future of the global economy.',
    location: 'فندق الفورسيزونز، الرياض',
    city: 'الرياض',
    startDate: '2026-10-27',
    endDate: '2026-10-29',
    availableBooths: 30,
    totalBooths: 100,
    type: 'conference',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 10000, exhibitors: 200, area: 20000 },
  },
  {
    id: 'ev-030',
    name: 'معرض جيتكس السعودية',
    nameEn: 'GITEX Saudi',
    description: 'معرض تقني ضخم ينطلق لأول مرة في السعودية يجمع الشركات التقنية الكبرى والشركات الناشئة والمستثمرين في حدث تقني عالمي.',
    descriptionEn: 'A massive tech exhibition launching for the first time in Saudi Arabia, gathering major tech companies, startups, and investors in a global tech event.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2027-01-20',
    endDate: '2027-01-23',
    availableBooths: 80,
    totalBooths: 350,
    type: 'technology',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 150000, exhibitors: 700, area: 60000 },
  },

  // ─── 3. Construction, Real Estate & Industry (بناء وعقار وصناعة) ──
  {
    id: 'ev-031',
    name: 'معرض Big 5 Construct Saudi',
    nameEn: 'Big 5 Construct Saudi',
    description: 'أكبر معرض للبناء والتشييد في السعودية يجمع أبرز شركات المقاولات وموردي مواد البناء والتصميم المعماري.',
    descriptionEn: 'The largest construction exhibition in Saudi Arabia gathering top contracting companies and suppliers of building materials and architectural design.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2026-02-09',
    endDate: '2026-02-12',
    availableBooths: 0,
    totalBooths: 200,
    type: 'exhibition',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 45000, exhibitors: 350, area: 40000 },
  },
  {
    id: 'ev-032',
    name: 'معرض مكة بيلدكس 2026',
    nameEn: 'Makkah Buildex 2026',
    description: 'معرض متخصص في العقار والبناء والصناعة والديكور، يجمع أبرز الشركات والمقاولين في المنطقة الغربية.',
    descriptionEn: 'A specialized exhibition in real estate, construction, industry, and décor, gathering top companies and contractors in the Western Region.',
    location: 'مركز المعارض، مكة المكرمة',
    city: 'مكة المكرمة',
    startDate: '2026-01-15',
    endDate: '2026-01-18',
    availableBooths: 0,
    totalBooths: 110,
    type: 'exhibition',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 25000, exhibitors: 180, area: 22000 },
  },
  {
    id: 'ev-033',
    name: 'معرض المطارات السعودية',
    nameEn: 'Saudi Airports Exhibition',
    description: 'معرض متخصص في تطوير المطارات وخدمات الطيران والتقنيات المطبقة في قطاع النقل الجوي.',
    descriptionEn: 'A specialized exhibition in airport development, aviation services, and technologies applied in the air transport sector.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2025-12-10',
    endDate: '2025-12-12',
    availableBooths: 0,
    totalBooths: 90,
    type: 'exhibition',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 20000, exhibitors: 120, area: 18000 },
  },
  {
    id: 'ev-034',
    name: 'معرض التصميم والديكور الدولي',
    nameEn: 'International Design & Décor Expo',
    description: 'معرض يستعرض أحدث صيحات التصميم الداخلي والديكور والأثاث الفاخر من أشهر الماركات العالمية والمحلية.',
    descriptionEn: 'An exhibition showcasing the latest trends in interior design, décor, and luxury furniture from top global and local brands.',
    location: 'مركز جدة للمعارض والمؤتمرات',
    city: 'جدة',
    startDate: '2026-05-20',
    endDate: '2026-05-23',
    availableBooths: 30,
    totalBooths: 100,
    type: 'exhibition',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 30000, exhibitors: 160, area: 20000 },
  },
  {
    id: 'ev-035',
    name: 'معرض الخمسة الكبار جدة',
    nameEn: 'Big 5 Jeddah',
    description: 'نسخة جدة من أكبر معرض للبناء والتشييد تركز على مشاريع التطوير العقاري في المنطقة الغربية.',
    descriptionEn: 'Jeddah edition of the largest construction exhibition focusing on real estate development projects in the Western Region.',
    location: 'مركز جدة للمعارض',
    city: 'جدة',
    startDate: '2026-09-14',
    endDate: '2026-09-17',
    availableBooths: 35,
    totalBooths: 150,
    type: 'exhibition',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 35000, exhibitors: 250, area: 30000 },
  },
  {
    id: 'ev-036',
    name: 'معرض ريستاتكس العقاري',
    nameEn: 'Restatex Real Estate Expo',
    description: 'أكبر معرض عقاري في السعودية يعرض المشاريع السكنية والتجارية الجديدة مع حلول التمويل العقاري.',
    descriptionEn: 'The largest real estate exhibition in Saudi Arabia showcasing new residential and commercial projects with real estate financing solutions.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2026-03-05',
    endDate: '2026-03-08',
    availableBooths: 20,
    totalBooths: 120,
    type: 'exhibition',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 50000, exhibitors: 200, area: 25000 },
  },
  {
    id: 'ev-037',
    name: 'معرض الصناعات السعودية',
    nameEn: 'Saudi Industries Exhibition',
    description: 'معرض يحتفي بالصناعات المحلية ويعرض منتجات "صنع في السعودية" من مختلف القطاعات الصناعية.',
    descriptionEn: 'An exhibition celebrating local industries and showcasing "Made in Saudi" products from various industrial sectors.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2026-12-01',
    endDate: '2026-12-04',
    availableBooths: 40,
    totalBooths: 160,
    type: 'exhibition',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 40000, exhibitors: 300, area: 35000 },
  },
  {
    id: 'ev-038',
    name: 'معرض النقل والخدمات اللوجستية',
    nameEn: 'Transport & Logistics Exhibition',
    description: 'معرض متخصص في قطاع النقل والخدمات اللوجستية يستعرض أحدث حلول الشحن والتخزين وسلاسل الإمداد.',
    descriptionEn: 'A specialized exhibition in transport and logistics showcasing the latest shipping, warehousing, and supply chain solutions.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2026-10-12',
    endDate: '2026-10-14',
    availableBooths: 25,
    totalBooths: 100,
    type: 'exhibition',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 20000, exhibitors: 150, area: 18000 },
  },
  {
    id: 'ev-039',
    name: 'معرض الحج والعمرة',
    nameEn: 'Hajj & Umrah Exhibition',
    description: 'معرض دولي يجمع مقدمي خدمات الحج والعمرة من حول العالم مع أحدث الحلول التقنية لخدمة ضيوف الرحمن.',
    descriptionEn: 'An international exhibition gathering Hajj and Umrah service providers worldwide with the latest technological solutions serving pilgrims.',
    location: 'مركز جدة للمعارض والمؤتمرات',
    city: 'جدة',
    startDate: '2026-01-20',
    endDate: '2026-01-22',
    availableBooths: 0,
    totalBooths: 120,
    type: 'exhibition',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 35000, exhibitors: 200, area: 22000 },
  },
  {
    id: 'ev-040',
    name: 'معرض الفنادق والضيافة',
    nameEn: 'Hotels & Hospitality Exhibition',
    description: 'معرض يجمع أبرز سلاسل الفنادق وشركات الضيافة لعرض أحدث الحلول والخدمات في قطاع الضيافة السعودي المتنامي.',
    descriptionEn: 'An exhibition gathering top hotel chains and hospitality companies to showcase the latest solutions and services in Saudi\'s growing hospitality sector.',
    location: 'مركز الرياض الدولي للمعارض',
    city: 'الرياض',
    startDate: '2026-09-08',
    endDate: '2026-09-10',
    availableBooths: 30,
    totalBooths: 110,
    type: 'exhibition',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 25000, exhibitors: 180, area: 20000 },
  },

  // ─── 4. Culture, Art & Sports (ثقافة وفنون ورياضة) ──────────
  {
    id: 'ev-041',
    name: 'معرض الرياض الدولي للكتاب',
    nameEn: 'Riyadh International Book Fair',
    description: 'أكبر معرض كتب في المنطقة يجمع أكثر من 2000 دار نشر من 30 دولة مع فعاليات ثقافية وندوات أدبية متنوعة.',
    descriptionEn: 'The largest book fair in the region gathering over 2000 publishers from 30 countries with diverse cultural events and literary seminars.',
    location: 'واجهة الرياض',
    city: 'الرياض',
    startDate: '2026-09-25',
    endDate: '2026-10-05',
    availableBooths: 55,
    totalBooths: 250,
    type: 'cultural',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 2000000, exhibitors: 2000, area: 40000 },
  },
  {
    id: 'ev-042',
    name: 'بينالي الدرعية للفن المعاصر',
    nameEn: 'Diriyah Contemporary Art Biennale',
    description: 'فعالية فنية عالمية تجمع أبرز الفنانين من حول العالم في حي جاكس التاريخي بالدرعية. منصة مثالية للعلامات التجارية الفاخرة.',
    descriptionEn: 'A world-class art event bringing together prominent artists from around the world in the historic JAX District of Diriyah. An ideal platform for luxury brands.',
    location: 'حي جاكس، الدرعية',
    city: 'الرياض',
    startDate: '2026-01-30',
    endDate: '2026-05-02',
    availableBooths: 18,
    totalBooths: 60,
    type: 'cultural',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 600000, exhibitors: 150, area: 30000 },
  },
  {
    id: 'ev-043',
    name: 'معرض بدايات للفن السعودي',
    nameEn: 'Bidayat Saudi Art Exhibition',
    description: 'معرض فني وثقافي يسلّط الضوء على بدايات الحركة الفنية السعودية ويستعرض أعمال رواد الفن التشكيلي في المملكة.',
    descriptionEn: 'An art and cultural exhibition highlighting the beginnings of the Saudi art movement and showcasing works by pioneering visual artists in the Kingdom.',
    location: 'المتحف الوطني السعودي',
    city: 'الرياض',
    startDate: '2026-01-27',
    endDate: '2026-04-11',
    availableBooths: 12,
    totalBooths: 40,
    type: 'cultural',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 200000, exhibitors: 80, area: 10000 },
  },
  {
    id: 'ev-044',
    name: 'كأس العالم للرياضات الإلكترونية',
    nameEn: 'Esports World Cup',
    description: 'بطولة عالمية كبرى للرياضات الإلكترونية تجذب جمهوراً ضخماً من عشاق الألعاب حول العالم مع فرص تجارية مميزة وجوائز بملايين الدولارات.',
    descriptionEn: 'A major global esports championship attracting a massive audience of gaming enthusiasts worldwide with outstanding commercial opportunities and millions in prizes.',
    location: 'بوليفارد سيتي',
    city: 'الرياض',
    startDate: '2026-07-15',
    endDate: '2026-08-25',
    availableBooths: 45,
    totalBooths: 180,
    type: 'sports',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 500000, exhibitors: 250, area: 50000 },
  },
  {
    id: 'ev-045',
    name: 'سباق فورمولا 1 - جائزة السعودية الكبرى',
    nameEn: 'Formula 1 Saudi Arabian Grand Prix',
    description: 'سباق فورمولا 1 على حلبة كورنيش جدة الشهيرة. أسرع حلبة شوارع في العالم مع أجواء احتفالية وفرص رعاية استثنائية.',
    descriptionEn: 'A Formula 1 race on the famous Jeddah Corniche Circuit. The fastest street circuit in the world with festive atmosphere and exceptional sponsorship opportunities.',
    location: 'حلبة كورنيش جدة',
    city: 'جدة',
    startDate: '2026-03-20',
    endDate: '2026-03-22',
    availableBooths: 15,
    totalBooths: 60,
    type: 'sports',
    status: 'active',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 350000, exhibitors: 100, area: 40000 },
  },
  {
    id: 'ev-046',
    name: 'سباق فورمولا إي (الدرعية)',
    nameEn: 'Formula E Diriyah E-Prix',
    description: 'سباق سيارات كهربائية في قلب الدرعية التاريخية. حدث رائد في الاستدامة والتقنية مع فعاليات جانبية متعددة.',
    descriptionEn: 'An electric car race in the heart of historic Diriyah. A pioneering event in sustainability and technology with multiple side events.',
    location: 'حلبة الدرعية',
    city: 'الرياض',
    startDate: '2026-01-23',
    endDate: '2026-01-24',
    availableBooths: 0,
    totalBooths: 50,
    type: 'sports',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 60000, exhibitors: 80, area: 25000 },
  },
  {
    id: 'ev-047',
    name: 'رالي داكار السعودية',
    nameEn: 'Dakar Rally Saudi Arabia',
    description: 'أصعب سباق تحمل في العالم يقام في الصحراء السعودية. تجربة مثيرة للجماهير مع معسكرات ومعارض مصاحبة.',
    descriptionEn: 'The world\'s toughest endurance race held in the Saudi desert. An exciting experience for fans with camps and accompanying exhibitions.',
    location: 'مناطق متعددة في المملكة',
    city: 'الرياض',
    startDate: '2026-01-05',
    endDate: '2026-01-17',
    availableBooths: 0,
    totalBooths: 40,
    type: 'sports',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 150000, exhibitors: 60, area: 15000 },
  },
  {
    id: 'ev-048',
    name: 'مهرجان البحر الأحمر السينمائي',
    nameEn: 'Red Sea International Film Festival',
    description: 'مهرجان سينمائي دولي يجمع صناع الأفلام والنجوم العالميين في جدة التاريخية مع عروض أفلام حصرية وحفلات سجادة حمراء.',
    descriptionEn: 'An international film festival bringing together filmmakers and global stars in historic Jeddah with exclusive screenings and red carpet events.',
    location: 'جدة التاريخية، البلد',
    city: 'جدة',
    startDate: '2026-12-04',
    endDate: '2026-12-13',
    availableBooths: 20,
    totalBooths: 70,
    type: 'cultural',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 100000, exhibitors: 120, area: 15000 },
  },
  {
    id: 'ev-049',
    name: 'مهرجان الجنادرية (التراث والثقافة)',
    nameEn: 'Janadriyah Festival (Heritage & Culture)',
    description: 'أعرق مهرجان تراثي في السعودية يحتفي بالثقافة والتراث السعودي مع عروض شعبية ومعارض حرفية ومسابقات إبل.',
    descriptionEn: 'The most prestigious heritage festival in Saudi Arabia celebrating Saudi culture and heritage with folk shows, craft exhibitions, and camel competitions.',
    location: 'الجنادرية، شمال شرق الرياض',
    city: 'الرياض',
    startDate: '2026-02-15',
    endDate: '2026-02-28',
    availableBooths: 0,
    totalBooths: 150,
    type: 'cultural',
    status: 'ended',
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 1500000, exhibitors: 400, area: 80000 },
  },
  {
    id: 'ev-050',
    name: 'معرض الصقور والصيد السعودي',
    nameEn: 'Saudi Falcons & Hunting Exhibition',
    description: 'معرض يحتفي بالتراث السعودي في الصقارة والصيد مع مزادات صقور نادرة ومعدات صيد حديثة ومسابقات تراثية.',
    descriptionEn: 'An exhibition celebrating Saudi heritage in falconry and hunting with rare falcon auctions, modern hunting equipment, and heritage competitions.',
    location: 'مركز الملك عبدالعزيز للمؤتمرات',
    city: 'الرياض',
    startDate: '2026-10-01',
    endDate: '2026-10-15',
    availableBooths: 35,
    totalBooths: 120,
    type: 'cultural',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1611689342806-0863700ce1e4?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 300000, exhibitors: 200, area: 25000 },
  },
  {
    id: 'ev-051',
    name: 'بطولة المملكة للمبارزة للسيدات',
    nameEn: 'Kingdom Ladies Fencing Championship',
    description: 'بطولة رياضية نسائية تجمع أفضل المبارزات في المملكة مع فعاليات رياضية وتوعوية مصاحبة.',
    descriptionEn: 'A women\'s sports championship gathering the best fencers in the Kingdom with accompanying sports and awareness events.',
    location: 'المدينة الرياضية',
    city: 'الرياض',
    startDate: '2026-06-10',
    endDate: '2026-06-14',
    availableBooths: 15,
    totalBooths: 40,
    type: 'sports',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1565992441121-4367c2967103?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 15000, exhibitors: 40, area: 8000 },
  },
  {
    id: 'ev-052',
    name: 'معرض قهوة أفريقيا 2026',
    nameEn: 'Africa Coffee Expo 2026',
    description: 'معرض متخصص في صناعة القهوة يجمع المنتجين والموردين والمحامص من أفريقيا والعالم مع تجارب تذوق حصرية.',
    descriptionEn: 'A specialized coffee industry exhibition gathering producers, suppliers, and roasters from Africa and the world with exclusive tasting experiences.',
    location: 'مركز المعارض',
    city: 'جدة',
    startDate: '2026-07-20',
    endDate: '2026-07-23',
    availableBooths: 25,
    totalBooths: 90,
    type: 'exhibition',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 30000, exhibitors: 120, area: 12000 },
  },
  {
    id: 'ev-053',
    name: 'سوق السفر السعودي 2026',
    nameEn: 'Saudi Travel Market 2026',
    description: 'معرض متخصص في قطاع السياحة والسفر يجمع شركات الطيران والفنادق ووكالات السفر والسياحة في منصة واحدة.',
    descriptionEn: 'A specialized exhibition in tourism and travel gathering airlines, hotels, and travel agencies on one platform.',
    location: 'مركز الرياض للمعارض',
    city: 'الرياض',
    startDate: '2026-10-05',
    endDate: '2026-10-08',
    availableBooths: 30,
    totalBooths: 120,
    type: 'exhibition',
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=800&h=400&fit=crop&q=80',
    stats: { expectedVisitors: 25000, exhibitors: 150, area: 18000 },
  },
];

// Helper to generate investor-specific descriptions
export function getInvestorEvents(): MerchantEvent[] {
  return saudiEventsDatabase.map((event) => ({
    ...event,
    id: `inv-${event.id}`,
    description: getInvestorDescription(event),
    descriptionEn: getInvestorDescriptionEn(event),
    availableBooths: Math.max(5, Math.floor(event.availableBooths * 0.6)),
    totalBooths: Math.floor(event.totalBooths * 0.4),
  }));
}

function getInvestorDescription(event: MerchantEvent): string {
  const templates: Record<string, string> = {
    entertainment: `${event.name} - فرصة استثمارية مميزة لتأجير المساحات والقاعات والمحلات التجارية. طلب عالي على المواقع المميزة.`,
    cultural: `${event.name} - فرصة لعرض مساحاتك للتجار والفنانين. احتياج كبير لمساحات العرض والمتاجر.`,
    technology: `${event.name} - فرصة لتأجير مساحات المعارض والقاعات بأسعار مميزة لشركات التقنية والابتكار.`,
    conference: `${event.name} - فرصة تأجير قاعات مؤتمرات ومساحات عرض ومكاتب مؤقتة للشركات المشاركة.`,
    exhibition: `${event.name} - فرصة تأجير مساحات عرض واسعة ومستودعات ومحلات تجارية للعارضين.`,
    sports: `${event.name} - فرصة لتأجير المساحات والمحلات التجارية والمطاعم للجماهير والزوار.`,
  };
  return templates[event.type] || event.description;
}

function getInvestorDescriptionEn(event: MerchantEvent): string {
  const templates: Record<string, string> = {
    entertainment: `${event.nameEn || event.name} - Prime investment opportunity for leasing spaces, halls, and shops. High demand for premium locations.`,
    cultural: `${event.nameEn || event.name} - Opportunity to showcase your spaces to merchants and artists. High demand for exhibition spaces and shops.`,
    technology: `${event.nameEn || event.name} - Opportunity to lease exhibition spaces and halls at premium rates for tech and innovation companies.`,
    conference: `${event.nameEn || event.name} - Opportunity to lease conference halls, exhibition spaces, and temporary offices for participating companies.`,
    exhibition: `${event.nameEn || event.name} - Opportunity to lease large exhibition spaces, warehouses, and retail shops for exhibitors.`,
    sports: `${event.nameEn || event.name} - Opportunity to lease spaces, retail shops, and restaurants for fans and visitors.`,
  };
  return templates[event.type] || (event.descriptionEn || event.description);
}
